const fs = require("node:fs");
const path = require("node:path");
const p = require("../package.json");
const fail = (msg) => { console.error(msg); process.exit(1); };
if (p.version !== "0.2.2") fail("version must be 0.2.2");
if (!p.keywords || !p.keywords.includes("pi-package")) fail("missing pi-package keyword");
if (!p.pi || !Array.isArray(p.pi.skills) || p.pi.skills.length !== 2) fail("pi.skills must list both skill dirs");
if (!p.pi.skills.includes("./skills/zig-0.16") || !p.pi.skills.includes("./skills/zig-tiger-style")) fail("unexpected pi.skills");
if (!Array.isArray(p.pi.extensions) || p.pi.extensions.length < 1) fail("pi.extensions must list our zls extension");
if (!p.pi.extensions.includes("./extensions/zls/index.ts")) fail("pi.extensions must include ./extensions/zls/index.ts");
const toolFile = path.join(__dirname, "../extensions/zls/zig-lsp-diagnostics.ts");
if (!fs.existsSync(toolFile)) fail("missing extensions/zls/zig-lsp-diagnostics.ts");
const toolSrc = fs.readFileSync(toolFile, "utf8");
if (!toolSrc.includes("zig_lsp_diagnostics")) fail("tool file must register zig_lsp_diagnostics");
if (!toolSrc.includes("publishDiagnostics")) fail("tool must wait for publishDiagnostics");
if (p.pi.extensions.includes("./node_modules/@narumitw/pi-lsp/dist/index.ts")) fail("do not register bundled pi-lsp entry");
console.log("package.json ok");
